PULP_APP = test
PULP_APP_SRCS = plp_bitreversal_xpulpv2.c plp_cfft_q16p_xpulpv2.c plp_cfft_q32p_xpulpv2.c plp_common_tables.c plp_const_structs.c main.c


PULP_CFLAGS = -O3 -I$(CURDIR)
PULP_LDFLAGS = -lm

include $(PULP_SDK_HOME)/install/rules/pulp.mk
